# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.5.1
mod_id=pingview
mod_name=Ping View
mod_description=Displays your and other players ping in the tab list.
mod_authors=karlsson1000
mod_license=MIT
maven_group=org.karlssonsmp.pingview

# Fabric Properties
minecraft_version=26.1.1
minecraft_version_range=[26.1,)
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# NeoForge
neo_version=26.1.1.0-beta
neo_version_range=[26.1,)

# Modmenu
modmenu_version=18.0.0-alpha.8

# Cloth config
cloth_config_version=26.1.154