# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.4
mod_id=pingview
mod_name=Ping View
mod_description=Displays your and other players ping in the tab list.
mod_authors=karlsson1000
mod_license=MIT
maven_group=org.karlssonsmp.pingview

# Fabric Properties
minecraft_version=26.1-rc-3
minecraft_version_range=[1.21.6,)
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Dependencies
fabric_version=0.143.14+26.1

# NeoForge
neo_version=21.11.35-beta
neo_version_range=[21.6,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20